### ISSUE TITLE
generate Sql

### ISSUE THREAD

**Issue by Almeonamy** [aspnet/EntityFramework.Docs.ru-ru#15]
The page has mistake. Meigrate.exe _can_ generate sql script for migration. It has option "/scriptFile".

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 105c0f35-0426-b31e-c804-c45bbb0a6f48
* Version Independent ID: 0d3bdfd4-be64-3251-703e-7173d3b3c6eb
* Content: [С помощью migrate.exe - EF6](https://docs.microsoft.com/ru-ru/ef/ef6/modeling/code-first/migrations/migrate-exe#feedback)
* Content Source: [entity-framework/ef6/modeling/code-first/migrations/migrate-exe.md](https://github.com/aspnet/EntityFramework.Docs.ru-ru/blob/live/entity-framework/ef6/modeling/code-first/migrations/migrate-exe.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by srvbpigh** [comment]
Hello, @Almeonamy
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [aspnet/EntityFramework.Docs #1740](https://github.com/aspnet/EntityFramework.Docs/issues/1740) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @Almeonamy

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/EntityFramework.Docs/issues/1740

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
